### ISSUE TITLE
Python 3.6 (nightly) problem

### ISSUE THREAD

**Issue by jayvdb** [ryanhiebert/tox-travis#9]
Only my Python 3.6 build fails (here: https://travis-ci.org/jayvdb/csl-data/jobs/108199025 ) with

```sh
$ pip install tox-travis
Collecting tox-travis
  Downloading tox_travis-0.3-py2.py3-none-any.whl
Collecting tox>=2.0 (from tox-travis)
  Downloading tox-2.3.1-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 7.8MB/s 
Collecting virtualenv>=1.11.2 (from tox>=2.0->tox-travis)
  Downloading virtualenv-14.0.6-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 368kB/s 
Requirement already satisfied (use --upgrade to upgrade): py>=1.4.17 in /home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages (from tox>=2.0->tox-travis)
Collecting pluggy<0.4.0,>=0.3.0 (from tox>=2.0->tox-travis)
  Downloading pluggy-0.3.1-py2.py3-none-any.whl
Installing collected packages: virtualenv, pluggy, tox, tox-travis
Successfully installed pluggy-0.3.1 tox-2.3.1 tox-travis-0.3 virtualenv-14.0.6
$ tox
```
```python
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6-dev/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/tox/session.py", line 38, in main
    config = prepare(args)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/tox/session.py", line 26, in prepare
    config = parseconfig(args)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/tox/config.py", line 208, in parseconfig
    pm.hook.tox_addoption(parser=parser)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/tox_travis.py", line 32, in tox_addoption
    desired_envs = get_desired_envs(config, version)
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/tox_travis.py", line 62, in get_desired_envs
    return split_env(travis_section.get(version, TOX_DEFAULTS.get(version)))
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/tox/config.py", line 801, in _split_env
    if '\n' in env:
TypeError: argument of type 'NoneType' is not iterable
```

It might be a tox bug, but if it is then I hope `tox-travis` can work around it.

**Comment by ryanhiebert** [comment]
Can you also post the tox section of your tox.ini?

**Comment by jayvdb** [comment]
It is as boring as it gets.
https://github.com/jayvdb/csl-data/blob/767bc9d2cc3608d9a23932e0ae28ba0df9ec7b5c/.travis.yml
```yaml
language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email: false
```

**Comment by jayvdb** [comment]
Do I need to include `py36` in `tox.ini` ?

**Comment by ryanhiebert** [comment]
I don't think that you'll need to do that, though you may decide that you should. Do you want 3.6 to run on your local tox runs?

My main question is what the value of the `TRAVIS_PYTHON_VERSION` environment variable is during this run. If it's `3.6`, then I can (and should) add that to the default configuration, so that it just works.

Unfortunately, I suspect that it will simply be `nightly`, and there's no good way for me keep `nightly` in sync with what's actually nightly at any given time.

Try adding this section to your `tox.ini`, and please let me know if it works:

```
[tox:travis]
nightly = py36
```

And I'm going to see about adding a better error message if/when this gets hit in the future.

**Comment by jayvdb** [comment]
Having everyone add
```
[tox:travis]
nightly = py36
```
multiplies the problem of keep "nightly" in sync.  We expect that `tox-travis` understands `tox` and Travis CI for us. ;-)
#11 is brilliant.
